# Generated by Django 4.0.3 on 2022-04-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_contact_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-id']},
        ),
    ]
