# Generated by Django 4.0.3 on 2022-04-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contact_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, height_field=100, upload_to='images/', width_field=100),
        ),
    ]
