# Generated by Django 4.0.3 on 2022-04-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, height_field=150, upload_to='images/', width_field=150),
        ),
    ]
